### ISSUE TITLE
https://github.com/aleph7/caffe links are not cloned properly

### ISSUE THREAD

**Issue by karthikeyanchenniappan** [noradaiko/caffe-ios-sample#1]
![screen shot 2015-07-20 at 4 14 20 pm](https://cloud.githubusercontent.com/assets/9041039/8774314/723d4654-2efa-11e5-9ef1-f5a7b973dba9.png)

/bin/sh: line 3: /Users/Macpro_ios_v2/caffe-ios-sample/caffe/bin/protoc: No such file or directory
cp: /Users/Macpro_ios_v2/Library/Developer/Xcode/DerivedData/CaffeApp-bbuyrkgpjrhlgeeafrxxurevjtxq/Build/Intermediates/CaffeApp.build/Debug-iphonesimulator/CaffeApp.build/DerivedSources/caffe/proto/caffe.pb.h: No such file or directory

**Comment by craftzdog** [comment]
You should clone this repo **recursively** to include submodule of caffe
And don't use libCaffe.a as static library. Build caffe from source within this project.

**Comment by karthikeyanchenniappan** [comment]
It works Thank U.

**Comment by karthikeyanchenniappan** [comment]
Hi Nora,
If possible ,please include the model_file , label_file , mean_file ,trained_file in your repo, to completely run and check the result of "caffe-ios-sample".This would be fine to move on the next steps with the caffe framework for iOS. 
Thanks
