### ISSUE TITLE
Out of memory issue

### ISSUE THREAD

**Issue by shrnjad** [noradaiko/caffe-ios-sample#5]
When I use the given model with the given image, the app runs out of memory on both iPhone 5s and 6. Did you encounter this, too?

**Comment by craftzdog** [comment]
No, I didn't, but I saw memory warnings several times while developing.
I've already released an app using this module though there're no issues of out-of-memory reported for now. It's working fine on iPhone 5s, 6 and 6s.

**Comment by shrnjad** [comment]
That's interesting, it crashed for me everytime during development. I have resorted to testing it with the GoogLeNet model, which is smaller. It works fine for me now, too.

Thanks for replying! :)

**Comment by craftzdog** [comment]
hmm, that's weird. Indeed the memory consumption depends on the size of model, so smaller model should be better. I recommend the Network in Network model which is smaller than GoogLeNet. Thanks!
