### ISSUE TITLE
/caffe-ios-sample-xcode7/caffe/lib/libglog.a(libglog_la-logging.o), building for iOS simulator, but linking in object file built for OSX, for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by jinxinbh** [noradaiko/caffe-ios-sample#6]
Thanks for your project.

I use Xcode  7.1 and meet this error.

Any ideas?

Best!

**Comment by craftzdog** [comment]
Please build it with Xcode 6.
Xcode changed the linker.

**Comment by afathi3** [comment]
Do you know how we can get this running on xcode 7 though?
I have another project in xcode 7 which I want to include the caffe in it.

**Comment by hartator** [comment]
First, thanks a lot for posting your example!

Same question here though. I had to downgrade to Xcode 6.4. That will be great if we have a way to integrate Caffe into Xcode 7+.
