### ISSUE TITLE
I can‘t run you model ,could you tell me how to figure out the question! Thanks！

### ISSUE THREAD

**Issue by chengliuAres** [noradaiko/caffe-ios-sample#7]
the Xcode told me : 
1 caffe-ios-sample-master/caffe/bin/protoc: No such file or directory
2 Library/Developer/Xcode/DerivedData/CaffeApp-bxiundasswcioecorfljnxviuqcn/Build/Intermediates/CaffeApp.build/Debug-iphonesimulator/CaffeApp.build/DerivedSources/caffe/proto/caffe.pb.h: No such file or directory

**Comment by craftzdog** [comment]
You have to checkout submodules.
