### ISSUE TITLE
 Showing All Issues /bin/sh: line 3: /Users/shashanktiwari/Downloads/caffe-ios-sample-master/caffe/bin/protoc: No such file or directory

### ISSUE THREAD

**Issue by tshank30** [noradaiko/caffe-ios-sample#8]

**Comment by tshank30** [comment]
cp: /Users/shashanktiwari/Library/Developer/Xcode/DerivedData/CaffeApp-dljeohfdehdatlgndrpjxxjlbdzf/Build/Intermediates/CaffeApp.build/Debug-iphonesimulator/CaffeApp.build/DerivedSources/caffe/proto/caffe.pb.h: No such file or directory

**Comment by tshank30** [comment]
I encountered these two issues while building the project. Please help.

**Comment by craftzdog** [comment]
Sorry but it's not maintained anymore. Try other frameworks.
